HoeenCoder/Wavelength

chat-plugins/poll.js, rooms.js
Allows up to 5 polls per room at once. Original PR was done by wgc, i added the forgotten help commands and the room part so it does not crash on entry
=> Multi polls

README.md
=> README: Fix Markdown

config/formats.js, mods/stacked/moves.js
=> Stacked meta

wavelength-plugins/profile.js
=> Add factions to profile

wavelength-plugins/factions.js
This commit fixes some glitches and adds some requests from desokoro.
=> Faction updates

wavelength-plugins/exp.js
These modifications will allow unlimited levels and give exp a popup on use for the individual user while not broadcasting or targeting anyone
=> Modify Exp functionality

wavelength-plugins/profile.js
Credit for the original code from panpawn
=> Profiles: Show Last Active Time

wavelength-plugins/roomrequest.js
If you use Monitor.adminlog it already uses:
if (Rooms('upperstaff')) {
therefore, it is unnecessary to type it before Monitor.adminlog
=> Room Requests: Fix typos & Simplifications

config/SGGame/items.json
=> Hyper Potion only heals 120 HP

config/SGGame/pokemon.json
=> SGGame: Add proper information for USUM stuff

WL.js, config/SGGame/items.json, game-cards/SGgame.js
This adds all 100 current tms and allows them to be learned
=> SGgame: Add Technical Machines

wavelength-plugins/factions.js
Currently if you use uppercase letters it will not work properly.
Thus I noticed it recorded as all lowercase etc and tested this and it works.
=> Factions: Fix bug with ATM

tournaments/index.js
Makes sure players are destroyed
=> Tours: Fix detrimental bug

config/SGGame/locations.js
Fixing a bunch of grammatical stuff in SGGame files
=> SGGame Grammar Revisions

wavelength-plugins/ssb.js
had to redo the pr. accidentally did it on my master branch which i updated for another pr
=> Ssbffa: setting customs

rooms.js, wavelength-plugins/survey.js
Thanks for the help @Arrays-Arr.
Anyways this is tested and ready to go!
=> Add Multi-Surveys

wavelength-plugins/survey.js
=> Surveys: Fix Timer crash

chat-plugins/modified.js, wavelength-plugins/misc.js
Or should i make it its own separate command
=> Add wl forums to /forums

wavelength-plugins/profile.js
I tested this @HoeenCoder it works and fixes the music not displaying glitch
=> Profile: Fix music not displaying glitch

room-battle.js, rooms.js
I recommend merging this after an update to main since i tested it on an updated to main version
=> FvF: Move start function

mods/wlssb/moves.js
=> WLSSB: Fix Meteor Madness

wavelength-plugins/survey.js
Fixes an error in survey's help
=> Survey: Help corrections

chat-plugins/hangman.js, chat-plugins/uno.js, chat.js, tournaments/index.js, wavelength-plugins/exp.js
This no longer encourages spam but allows a user to gain exp every 30 seconds since their last message for 15 minutes @HoeenCoder please hold off on merging for a bit as i need to double check everything
=> Exp: automation

wavelength-plugins/profile.js
Not all of this is mine, so I would like to credit Prince Sky & Execute
=> Profiles: Restyle using ${} and add a few things

wavelength-plugins/survey.js
Idk if you want survey to sync with modchat but why not right?
=> Block Locked users from answering surveys as well as modchat

config/formats.js, data/wlssb-data.txt, mods/wlssb/abilities.js, mods/wlssb/items.js, mods/wlssb/moves.js, mods/wlssb/pokedex.js, mods/wlssb/random-teams.js, mods/wlssb/statuses.js
Added the newest staff
New Alfastorm and me
RIP HiroZ
Other tweaks when needed
=> WLSSB new stuff and Fix formats

wavelength-plugins/profile.js
=> Implement Last Active Command

wavelength-plugins/ssb.js
Made it look a lot neater, etc (also fixed every known typo)
=> SSB: Restyle code using ${}

wavelength-plugins/exp.js, wavelength-plugins/factions.js
@DesoGit make sure everythings here @HoeenCoder i uuuuhhh did a thing-a-majig pls review!
=> Factions: Faction bank rewrites + shop

users.js, wavelength-plugins/friends.js
@Mystifi @HoeenCoder i know this is pretty basic but it's a start. tested and works btw
=> Friends: Create friend list

config/formats.js, mods/digimon/abilities.js, mods/digimon/moves.js, mods/digimon/pokedex.js, mods/digimon/random-teams.js, mods/digimon/statuses.js, mods/digimon/typechart.js
=> Digimon Showdown

wavelength-plugins/ssb.js
=> Allow existing abilities as custom abilities

mods/digimon/pokedex.js
I added stage data to every digimon so that it can be loaded into the Digimon Profiler Alfa and I are working on. Who knows maybe it can also be used for teir rules.
=> Stage data added.

mods/digimon/random-teams.js
The following fixes have been applied to
MetalGreymonVIrus -> MetalGreymonVirus
Added Name code to MetalGreymon Vaccine called "MetalGreymon"
Added name code to regular Meicrackmon.
Added name code to Cherubimon Evil called "Cherubimon"
=> MetalGreymons, Meicrackmon & Cherubimon Evil.

mods/digimon/moves.js
Glad its not a real heart attack, just a typo error. XD
=> Heart Attack -> Hearts Attack

mods/wlssb/items.js, mods/wlssb/moves.js
=> WLSSB: Bug Fixes

mods/digimon/learnsets.js
Sorry to give you the cold shoulder on Sheer Cold. It would Ice the Digipedia and may give some fans a chilling feeling.
=> No Sheer Cold

wavelength-plugins/digimon.js
Commands to help users to better understand the specifics of each digimon and how they can be used in battle.
=> Add digimon showdown chat-plugin

mods/digimon/moves.js
burning heart: Now has its priority of 0 coded.
Panicattack: Now has a short description.
pitbomb: Now has flags.
Added secondary false to
evilcharm, solarray, deathhand, pummelwhack, raremetalpoop, antidigibeam, lustershot, necromagic, hypercannon, blazeblaster, aerialattack, spiralsword, celestialarrow, metalmeteor, deadlybomb, flowercannon, smilebomber, genocideattack, hornbuster, lightningjavelin, berserkthinking, gigadestroyer, revengeflame, energybomb, grislywing, pitbomb, musicalfist, rootbind and extremepoopdeath
File found these while making us a move script :)
=> Bunch of little bug fixes

game-cards/SGgame.js
Also uses move2 instead of pokemon.moves[m]
=> fix v2 bugs, for real this time

package.json, wavelength-plugins/profile.js
Removes geoip-lite-country due to returning 404 - Includes removal of function from profile.js and package.json
=> Remove geoip-lite-country

wavelength-plugins/dice.js, wavelength-plugins/economy.js
=> Replace: Economy.logDice -> Economy.logTransaction
